### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no rocksaw in java.library.path

### ISSUE THREAD

**Issue by anvide** [mlaccetti/rocksaw#9]
I installed Visual C ++.Add maven on Netbean
```
  <dependency>
            <groupId>com.github.mlaccetti</groupId>
            <artifactId>rocksaw</artifactId>
            <version>1.1.0</version>
        </dependency> 
```
But when I run the program 
```
  InetAddress inetAddress = InetAddress.getByName("www.microsoft.com");

        RawSocket socket = new RawSocket();
        socket.bind(inetAddress);
        System.out.println(socket.isOpen());
```
I always get the error message
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no rocksaw in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1122)
	at www.NewClass1.main(NewClass1.java:23)
```
What do I need to do to fix it

**Comment by Multiple-Personality** [comment]
cd C:\Users\NoFear\Downloads\rocksaw-1.0.3\src\jni
g++ -c -I"C:\Program Files\Java\jdk1.8.0_261\include" -I"C:\Program Files\Java\jdk1.8.0_261\include\win32" -c RawSocket.c -o RawSocket.o

ERROR............................
Need to generate dll but when I try to compile I get error. Please help me
